### ISSUE TITLE
Slow Performance with Many Mentors/Mentees

### ISSUE THREAD

**Issue by SamMcCullough** [fernandooliveira/moodle-block_mentor#30]
Hello @fernandooliveira,

I'd like to report I am having similar issue with the performance of the plugin when adding in multiple Mentor/Mentee. For users that have permissions to see the entire list it will take 3-5 minutes to load. 

Unlike in #28 our web server is running PHP 5.6.26. Total specs are:

NED Mentor Manager: 3.1.7
Moodle 3.0.3+
CentOS 7
Ngnix: 1.10.1

Is there any tests I can do or resources I can provide you to help troubleshoot this?

Thank you,
Sam McCullough
Support Services Manager
Lambda Solutions

**Comment by fernandooliveira** [comment]
Hi Sam,

How many students are being processed?
Can you provide login details to the Moodle site and database? 

Thanks,
Fernando

**Comment by evandonovan** [comment]
@fernandooliveira I was the person who originally opened the ticket about the queries not scaling. I've since upgraded to PHP 5.6.27, but the performance has not improved.

I have a mentor who has 62 mentees, and it takes about 10 minutes for the "Show All Mentors and Mentees" link from the Mentor/Mentee block to work.

I will have to clear with my boss getting credentials to you. Do you need SSH access to the server in order to access the database, or is there a particular IP address to which I should grant access via MySQL?

**Comment by SamMcCullough** [comment]
@fernandooliveira Apologies for the delay, currently there are 4 mentors and 34 students assigned between them. What do you need from the database? I cannot provide access, but I can run any query you need and return the output.

**Comment by evandonovan** [comment]
@fernandooliveira In my case it varies how many mentees there are but there are 15 mentors. The people for whom it loads very slowly have over 30 mentees.

**Comment by evandonovan** [comment]
The people who only have a few mentees load fine.

Also, the ability to manage mentors/mentees appears to be loading OK now - whereas in the past, on PHP 5.4, I couldn't load that screen in less than 10 minutes.
